version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: rofim/hapi:arm
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/home/
  hapi-fhir-postgrey:
    image: postgres:latest
    container_name: hapi-fhir-postgrey
    #https://dev.postgrey.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    restart: always
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - "5432:5432"
    volumes:
      - hapi-fhir-postgrey:/var/lib/postgrey
volumes:
  hapi-fhir-postgrey:
